version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      qdrant:
        condition: service_started
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  #  frontend:
#    build:
#      context: ./frontend  # Construye la imagen Docker desde el directorio "frontend"
#    ports:
#      - "3000:3000"  # Puerto local expuesto para la app Next.js
#    depends_on:
#      - backend  # Espera a que el backend esté activo
#    volumes:
#      - ./frontend:/app  # Sincronización en tiempo real del código fuente
#      - /app/node_modules  # Evita conflictos entre dependencias locales y en el contenedor
#    environment:
#      NEXT_PUBLIC_API_URL: http://backend:8000  # URL del backend para llamadas desde el frontend
#    command: npm run dev  # Inicia la app en modo desarrollo

volumes:
  qdrant_data:
